export enum Assets {
	'TOMBSTONES__3' = 'tombstones/3',
	'TOMBSTONES__2' = 'tombstones/2',
	'TOMBSTONES__1' = 'tombstones/1',
	'SAW__VERT' = 'saw/vert',
	'SAW__HOR' = 'saw/hor',
	'HANDS__2' = 'hands/2',
	'HANDS__1' = 'hands/1',
	'FORMS__TRIANGLE' = 'forms/triangle',
	'FORMS__RHOMBUS' = 'forms/rhombus',
	'FORMS__RECTANGLE' = 'forms/rectangle',
	'FORMS__ELLIPSE' = 'forms/ellipse',
	'FIREBALLS__1' = 'fireballs/1',
	'ENEMIES__2' = 'enemies/2',
	'ENEMIES__1' = 'enemies/1',
	'CRAFT_BUTTONS__THOMBSTONE' = 'craft-buttons/thombstone',
	'CRAFT_BUTTONS__HANDS' = 'craft-buttons/hands',
	'CRAFT_BUTTONS__FIRE' = 'craft-buttons/fire',
	'CRAFT_BUTTONS__CIRCULAR' = 'craft-buttons/circular',
	'CRAFT_BUTTONS__CANDLES' = 'craft-buttons/candles',
	'CASTER' = 'caster',
	'CANDLES__3' = 'candles/3',
	'CANDLES__2' = 'candles/2',
	'CANDLES__1' = 'candles/1',
	'BG' = 'bg'
}
