export default {
	sceneFadeDuration: 200,
	debug: import.meta.env.VITE_DEBUG === 'true',
	showFps: import.meta.env.VITE_DEBUG === 'true',
	bugTracking: import.meta.env.VITE_BUG_TRACKING === 'true',
	stage: {
		startBones: 50,
		startMobAmount: 3,
		maxStageMobAmount: 16,
		waveInterval: 1000,
		bonusBone: 0.05,
		bonusBoneCost: 10,
		boneCost: 1,
	},
	character: {
		damage: 1,
		minSpeed: 50,
		speedOffset: 50,
		minHealth: 1,
		maxHealth: 7,
		hitAnimationSpeed: 300,
		attackInterval: 2000,
	},
	objects: {
		statue: {
			strength: 30,
			attackInterval: 5000,
			aimTime: 2000,
			damage: 4,
		},
		hands: {
			damage: 1,
			cost: 10,
			strength: 2,
			repairCost: 10,
			maxAmount: 16,
		},
		saw: {
			damage: 2,
			strength: 3,
			cost: 12,
			repairCost: 5,
			speed: 1500,
			interval: 1000,
			fadeSpeed: 100,
		},
		fireBall: {
			damage: 3,
			strength: 4,
			cost: 15,
			repairCost: 8,
			maxAmount: 8,
		},
		tombstones: {
			damage: 4,
			strength: 5,
			cost: 20,
			repairCost: 15,
			attackInterval: 5000,
			smokeSpeed: 500,
		},
		candles: {
			cost: 50,
		},
	},
};
